[package]
name = "enigmacoreenclave"
version = "0.9.8"
authors = ["Enigma"]

[lib]
name = "enigmacoreenclave"
crate-type = ["staticlib"]

[features]
default = []

[dependencies]
lazy_static = {version = "1.0.1", features = ["spin_no_std"] }
enigma-tools-t = {path = "../../enigma-tools-t"}
failure = "0.1.1"
failure_derive="0.1.1"
rustc-hex = { git = "https://github.com/enigmampc/rustc-hex.git", rev = "sgx-master" }
tiny-keccak = "1.4.1"
ethabi = { git = "https://github.com/enigmampc/ethabi.git", rev = "sgx-v5.1.0", default-features = false}
error-chain = { git = "https://github.com/enigmampc/error-chain.git", rev = "sgx-0.11.0", default-features = false }
etcommon-rlp = {git = "https://github.com/enigmampc/etcommon-rs.git", rev = "develop", default-features = false}


[dependencies.sputnikvm-network-classic]
git = "https://github.com/enigmampc/sputnikvm.git"
rev = "develop"
default-features = false

[dependencies.sputnikvm]
git = "https://github.com/enigmampc/sputnikvm.git"
rev = "develop"
default-features = false

[dependencies.etcommon-hexutil]
git = "https://github.com/enigmampc/etcommon-rs.git"
rev = "develop"
default-features = false

[dependencies.etcommon-bigint]
git = "https://github.com/enigmampc/etcommon-rs.git"
rev = "develop"
default-features = false
features = ["rlp"]

[target.'cfg(not(target_env = "sgx"))'.dependencies.sgx_types]
git = "https://github.com/baidu/rust-sgx-sdk.git"
rev = "v1.0.0"

[target.'cfg(not(target_env = "sgx"))'.dependencies.sgx_tstd]
git = "https://github.com/baidu/rust-sgx-sdk.git"
rev = "v1.0.0"

[target.'cfg(not(target_env = "sgx"))'.dependencies.sgx_trts]
git = "https://github.com/baidu/rust-sgx-sdk.git"
rev = "v1.0.0"

# quote
[target.'cfg(not(target_env = "sgx"))'.dependencies.sgx_tse]
git = "https://github.com/baidu/rust-sgx-sdk.git"
rev = "v1.0.0"

# no real reason added while debugging create_report
[target.'cfg(not(target_env = "sgx"))'.dependencies.sgx_tdh]
git = "https://github.com/baidu/rust-sgx-sdk.git"
rev = "v1.0.0"

[target.'cfg(not(target_env = "sgx"))'.dependencies.sgx_tservice]
git = "https://github.com/baidu/rust-sgx-sdk.git"
rev = "v1.0.0"


[target.'cfg(not(target_env = "sgx"))'.dependencies.sgx_alloc]
git = "https://github.com/baidu/rust-sgx-sdk.git"
rev = "v1.0.0"

# sealing testing not all required.
[target.'cfg(not(target_env = "sgx"))'.dependencies.sgx_tseal]
git = "https://github.com/baidu/rust-sgx-sdk.git"
rev = "v1.0.0"
# delete rand
[target.'cfg(not(target_env = "sgx"))'.dependencies.sgx_rand]
git = "https://github.com/baidu/rust-sgx-sdk.git"
rev = "v1.0.0"
# end of sealing

[target.'cfg(not(target_env = "sgx"))'.dependencies.sgx_tunittest]
git = "https://github.com/baidu/rust-sgx-sdk.git"
rev = "v1.0.0"

[dependencies.ring]
git = "https://github.com/enigmampc/ring.git"
rev = "sgx-0.12.1"