[package]
name = "enigma_principal_app"
version = "0.1.3"
authors = ["Enigma <support@enigma.co>"]
build = "build.rs"

[dependencies]
enigma-tools-u = {path = "../../enigma-tools-u"}

ethabi = "6.0"
base64 = "0.10.0"
libc = "0.2.41"
etcommon-rlp = "0.2"
failure = "=0.1.1"
failure_derive="=0.1.1"
web3 = "0.5.1"
rustc-hex = "1.0.0"
tokio-core = "0.1.17"
serde_json = "1.0"
serde = "1.0.66"
serde_derive = "1.0.70"
structopt = "0.2.10"
url = "1.7.1"
tiny-keccak = "1.4.2"
colour = "0.2.1"
dirs = "1.0"
jsonrpc-core = { git = "https://github.com/paritytech/jsonrpc" }
jsonrpc-minihttp-server = { git = "https://github.com/paritytech/jsonrpc" }

sgx_types = { git = "https://github.com/baidu/rust-sgx-sdk.git", rev = "v1.0.4" }
sgx_urts = { git = "https://github.com/baidu/rust-sgx-sdk.git", rev = "v1.0.4" }
