[package]
name = "enigma-tools-t"
version = "0.1.3"
authors = ["Elichai-Turkel <elichai@enigma.co>"]
description = "Tools used by the trusted part of the Enigma core and Principal node."

[dependencies]
enigma-types = { path = "../enigma-types" }
tiny-keccak = "1.4.1"
failure_derive="=0.1.1"
failure = { version = "=0.1.1", default-features = false, features = ["derive"] }
etcommon-rlp = {version = "0.2", default-features = false}
etcommon-hexutil = { version = "0.2", default-features = false }
etcommon-bigint = { version = "0.2", default-features = false, features = ["rlp"] }
ethabi = { git = "https://github.com/enigmampc/ethabi.git", rev = "sgx-v6.1.0", default-features = false}


#libsecp256k1 = { git = "https://github.com/enigmampc/libsecp256k1-rs.git" }
libsecp256k1 = "0.2.1"
rmp-serde = { git = "https://github.com/enigmampc/msgpack-rust.git", rev =  "sgx-v1.0.4" }
serde = { git = "https://github.com/baidu/rust-sgx-sdk.git", rev = "v1.0.4" }
serde_derive = { git = "https://github.com/baidu/rust-sgx-sdk.git", rev = "v1.0.4" }
serde_json = { git = "https://github.com/baidu/rust-sgx-sdk.git", rev = "v1.0.4" }
json-patch = { git = "https://github.com/enigmampc/json-patch.git", rev = "sgx-0.2.2-v1.0.4" }

wasmi = { git = "https://github.com/baidu/rust-sgx-sdk.git", rev = "v1.0.4" }
ring = { git = "https://github.com/baidu/rust-sgx-sdk.git", rev = "v1.0.4" }

sgx_types = { git = "https://github.com/baidu/rust-sgx-sdk.git", rev = "v1.0.4" }
sgx_tstd = { git = "https://github.com/baidu/rust-sgx-sdk.git", rev = "v1.0.4" }
sgx_trts = { git = "https://github.com/baidu/rust-sgx-sdk.git", rev = "v1.0.4" }
sgx_tse = { git = "https://github.com/baidu/rust-sgx-sdk.git", rev = "v1.0.4" }
sgx_tseal = { git = "https://github.com/baidu/rust-sgx-sdk.git", rev = "v1.0.4" }


