[package]
name = "enigma-core-app"
version = "0.1.3"
authors = ["Enigma <support@enigma.co>"]
build = "build.rs"

[dependencies]
enigma-tools-u = {path = "../../enigma-tools-u"}
enigma-types = { path = "../../enigma-types" }

base64 = "0.10.0"
zmq = "0.8"
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
failure = "=0.1.1"
failure_derive="=0.1.1"
rustc-hex = "1.0.0" # 2.0.1?
reqwest = "0.9.4"
dirs = "1.0"
rocksdb = { git = "https://github.com/elichai/rust-rocksdb.git" } # This is temporary, until PR is merged
db-key = "0.0.5"
lazy_static = "1.1.0"
byteorder = "1.2"
lru-cache = "0.1.1"

parity-wasm = "0.31" # 0.35?
pwasm-utils = { git = "https://github.com/enigmampc/wasm-utils.git" } # TODO: add a version specific branch.

sgx_types = { git = "https://github.com/baidu/rust-sgx-sdk.git", rev = "v1.0.4" }
sgx_urts = { git = "https://github.com/baidu/rust-sgx-sdk.git", rev = "v1.0.4" }

[dev-dependencies]
tempdir = "0.3.7"
rmp-serde = "0.13.7"
libsecp256k1 = "0.2.1"
rand = "0.4.3"
ring = "0.13.5"