[package]
name = "enigma-core-app"
version = "0.1.3"
authors = ["Enigma <support@enigma.co>"]
build = "build.rs"

[dependencies]
enigma-tools-u = {path = "../../enigma-tools-u"}
enigma-types = { path = "../../enigma-types" }
enigma-crypto = { path = "../../enigma-crypto" }
futures = "0.1.25"
tokio = "0.1.13"
tokio-zmq = "0.9.0"
base64 = "0.10.0"
zmq = "0.9.0"
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
rmp-serde = { git = "https://github.com/3Hren/msgpack-rust.git" } # This is because of a bug of incompatibility https://github.com/3Hren/msgpack-rust/issues/189
failure = "0.1.3"
failure_derive = "0.1.3"
rustc-hex = "1.0.0" # 2.0.1?
reqwest = "0.9.5"
dirs = "1.0.4"
rocksdb = { git = "https://github.com/elichai/rust-rocksdb.git" } # This is temporary, until PR is merged
lazy_static = "1.2.0"
byteorder = "1.2.7"
lru-cache = "0.1.1"
log = "0.4.6"

sgx_types = { git = "https://github.com/baidu/rust-sgx-sdk.git", rev = "v1.0.4" }
sgx_urts = { git = "https://github.com/baidu/rust-sgx-sdk.git", rev = "v1.0.4" }

[dev-dependencies]
ethabi = "6.1.0"
tempfile = "3.0"