[package]
name = "enigma_principal_enclave"
version = "0.1.3"
authors = ["Enigma <support@enigma.co>"]

[lib]
name = "enigma_principal_enclave"
crate-type = ["staticlib"]

[features]
default = []

[dependencies]
spin = "=0.4.8"
lazy_static = {version = "1.0.1", features = ["spin_no_std"] }
enigma-tools-t = {path = "../../enigma-tools-t"}

[target.'cfg(not(target_env = "sgx"))'.dependencies.sgx_types]
git = "https://github.com/baidu/rust-sgx-sdk.git"
rev = "v1.0.0"

[target.'cfg(not(target_env = "sgx"))'.dependencies.sgx_tstd]
git = "https://github.com/baidu/rust-sgx-sdk.git"
rev = "v1.0.0"

[target.'cfg(not(target_env = "sgx"))'.dependencies.sgx_trts]
git = "https://github.com/baidu/rust-sgx-sdk.git"
rev = "v1.0.0"

# quote
[target.'cfg(not(target_env = "sgx"))'.dependencies.sgx_tse]
git = "https://github.com/baidu/rust-sgx-sdk.git"
rev = "v1.0.0"

# no real reason added while debugging create_report
[target.'cfg(not(target_env = "sgx"))'.dependencies.sgx_tdh]
git = "https://github.com/baidu/rust-sgx-sdk.git"
rev = "v1.0.0"

[target.'cfg(not(target_env = "sgx"))'.dependencies.sgx_tservice]
git = "https://github.com/baidu/rust-sgx-sdk.git"
rev = "v1.0.0"


[target.'cfg(not(target_env = "sgx"))'.dependencies.sgx_alloc]
git = "https://github.com/baidu/rust-sgx-sdk.git"
rev = "v1.0.0"

# sealing testing not all required.
[target.'cfg(not(target_env = "sgx"))'.dependencies.sgx_tseal]
git = "https://github.com/baidu/rust-sgx-sdk.git"
rev = "v1.0.0"
# delete rand
[target.'cfg(not(target_env = "sgx"))'.dependencies.sgx_rand]
git = "https://github.com/baidu/rust-sgx-sdk.git"
rev = "v1.0.0"
# end of sealing

[target.'cfg(not(target_env = "sgx"))'.dependencies.sgx_tunittest]
git = "https://github.com/baidu/rust-sgx-sdk.git"
rev = "v1.0.0"
